version: '3.8'
services:
  devcontainer:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    container_name: dev-pick_ik
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=99
    extra_hosts:
      - pick_ik:127.0.0.1
    hostname: pick_ik
    image: pick_ik:latest
    network_mode: host
    privileged: true
    user: dev
    volumes:
      - ../:/home/dev/pick_ik
      - ~/.ssh:/home/dev/.ssh:ro
      - ~/.gitconfig:/home/dev/.gitconfig:ro
      - ~/.local/.pick_ik/ccache:/home/dev/.ccache
      - ~/.local/.pick_ik/log:/home/dev/.ros/log
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
    working_dir: /home/pick_ik
